<a href="https://colab.research.google.com/github/kanokwan-hongsopa/PythonDataViz2026/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**HW** 5 เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด

- (2,3)*(3,2)
- (4,4)*(4,1)
- (2,2)*(2,2)

In [31]:
import numpy as np

In [32]:
def mat_mul(A,B):
    C = np.zeros((A.shape[0],B.shape[1]))#เตรียมขนาดของ matrix ผลลัพธ์
    for r_a in range(A.shape[0]):
        for c_b in range(B.shape[1]):
            for every_element in range(A.shape[1]):
                C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
    return C

In [33]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[1,2],[3,4],[5,6]])
mat3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
mat4 = np.array([[1],[2],[3],[4]])
mat5 = np.array([[1,2],[3,4]])
mat6 = np.array([[1,2],[3,4]])

In [43]:
print(mat1.shape)
print(mat2.shape)
print(mat3.shape)
print(mat4.shape)
print(mat5.shape)
print(mat6.shape)

(2, 3)
(3, 2)
(4, 4)
(4, 1)
(2, 2)
(2, 2)


In [35]:
mat_mul(mat1,mat2)

array([[22., 28.],
       [49., 64.]])

In [36]:
mat_mul(mat3,mat4)

array([[ 30.],
       [ 70.],
       [110.],
       [150.]])

In [37]:
mat_mul(mat5,mat6)

array([[ 7., 10.],
       [15., 22.]])